# Generated by Django 3.1.7 on 2021-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='namereceiver',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
